window.PUSH_PRESENT_CATEGORIES = [
  {
    id: "milk-fridge",
    title: "Upstairs Milk Fridge",
    subtitle: "True compressor refrigerators only",
    note: "Breast milk must stay at 40°F / 4°C or colder. Add an appliance thermometer and verify the temperature before storing milk. Cosmetic thermoelectric coolers were excluded.",
    icon: "currency.png",
  },
  {
    id: "bottle-warmer",
    title: "Bottle Warmer",
    subtitle: "Fast feeds beside the gaming desk",
    note: "Warm water-bath models are gentler for breast milk. Always swirl and test the milk temperature before feeding.",
    icon: "recommendations.png",
  },
  {
    id: "baby-space",
    title: "Baby's Craft-Room Space",
    subtitle: "A safe place nearby while Lulu games",
    note: "Floor use only. For sleep, use a CPSC-compliant crib, bassinet, portable crib, or play yard with a firm flat surface and fitted sheet only. Never place or anchor one on a tabletop.",
    icon: "recommendations.png",
  },
  {
    id: "office-chair",
    title: "Healing-Friendly Chair",
    subtitle: "Cute enough for Lulu, adjustable enough for long sessions",
    note: "Comfort is personal. These Costco options prioritize deep cushioning and lumbar support; confirm the current warehouse price and return terms.",
    icon: "recommendations.png",
  },
  {
    id: "light-art",
    title: "Light-Up Final Fantasy Art",
    subtitle: "Eorzea, Amaurot, Spira, and Vana'diel",
    note: "Etsy prices and availability change frequently. The links open the exact indexed listing where available; confirm seller details before ordering.",
    icon: "glamour_plate.png",
  },
  {
    id: "desk-mat",
    title: "Desk Upgrade",
    subtitle: "Custom Lulu art or a cleaner monitor setup",
    note: "Choose between one personalized RGB desk mat and two practical monitor risers. Measure the desk before ordering.",
    icon: "limit_break.png",
  },
];

window.PUSH_PRESENT_PRODUCTS = [
  {
    id: "fridge-frigidaire-pink-16",
    category: "milk-fridge",
    title: "Frigidaire 1.6 cu. ft. Retro Refrigerator",
    retailer: "Walmart",
    price: "$118.00",
    rating: "4.1 · 1,399 reviews",
    badge: "Cutest compact pick",
    note: "Pink compressor refrigerator with chiller compartment and side bottle opener. Small enough for an upstairs office without relying on thermoelectric cooling.",
    specs: ["1.6 cu. ft.", "Pink retro shell", "Adjustable thermostat"],
    image: "assets/products/fridge-frigidaire-pink.jpg",
    url: "https://www.walmart.com/ip/983936626",
  },
  {
    id: "fridge-bangson-pink-17",
    category: "milk-fridge",
    title: "BANGSON 1.7 cu. ft. Mini Fridge",
    retailer: "Walmart",
    price: "$119.99",
    rating: "4.5 · 44 reviews",
    badge: "Best pink value",
    note: "A pink compressor model with freezer compartment, low-noise positioning, and more conventional interior storage.",
    specs: ["1.7 cu. ft.", "Freezer compartment", "Low-noise design"],
    image: "assets/products/fridge-bangson-pink.jpg",
    url: "https://www.walmart.com/ip/18938167803",
  },
  {
    id: "fridge-frigidaire-coral-32",
    category: "milk-fridge",
    title: "Frigidaire 3.2 cu. ft. Retro Refrigerator",
    retailer: "Walmart",
    price: "$158.00",
    rating: "4.0 · 2,088 reviews",
    badge: "Best capacity",
    note: "Coral retro refrigerator with chiller and substantially more room for milk, drinks, pump parts, and snacks.",
    specs: ["3.2 cu. ft.", "Coral finish", "Chiller compartment"],
    image: "assets/products/fridge-frigidaire-coral.jpg",
    url: "https://www.walmart.com/ip/598804573",
  },
  {
    id: "fridge-frigidaire-pink-32",
    category: "milk-fridge",
    title: "Frigidaire 3.2 cu. ft. Retro Refrigerator in Pink",
    retailer: "Walmart",
    price: "Check current price",
    rating: "Full-size compact option",
    badge: "Roomiest pink pick",
    note: "The pink version of the larger compressor refrigerator, with room for bottles, pump parts, drinks, and snacks.",
    specs: ["3.2 cu. ft.", "Pink retro finish", "Adjustable thermostat"],
    image: "assets/products/fridge-frigidaire-pink.jpg",
    url: "https://www.walmart.com/search?q=Frigidaire+3.2+cu+ft+retro+refrigerator+pink",
  },
  {
    id: "fridge-bangson-white-17",
    category: "milk-fridge",
    title: "BANGSON 1.7 cu. ft. Mini Fridge in White",
    retailer: "Walmart",
    price: "Check current price",
    rating: "Compact compressor model",
    badge: "Best clean white pick",
    note: "A clean white alternative to the pink BANGSON with the same compact footprint and separate freezer compartment.",
    specs: ["1.7 cu. ft.", "White finish", "Freezer compartment"],
    image: "assets/products/fridge-bangson-pink.jpg",
    url: "https://www.walmart.com/search?q=BANGSON+1.7+cu+ft+mini+fridge+white",
  },
  {
    id: "warmer-philips-avent",
    category: "bottle-warmer",
    title: "Philips Avent Premium Fast Warmer",
    retailer: "Target",
    price: "$46.99",
    rating: "3.6 · 778 ratings",
    badge: "Simplest controls",
    note: "Smart temperature control detects starting temperature, warms evenly, defrosts, and holds temperature for up to 60 minutes.",
    specs: ["Auto shutoff", "No hot spots", "Defrost mode"],
    image: "assets/products/warm-philips.png",
    url: "https://www.target.com/p/-/A-80178789",
  },
  {
    id: "warmer-momcozy-mw01",
    category: "bottle-warmer",
    title: "Momcozy MW01 6-in-1 Warmer",
    retailer: "Target",
    price: "$33.99",
    rating: "4.1 · 344 ratings",
    badge: "Best value",
    note: "Fast 2–5 minute warming plus thaw, food heat, steam, and keep-warm modes. Fits bottles and milk bags up to 11 oz.",
    specs: ["2–5 minute warm", "Fits milk bags", "6 functions"],
    image: "assets/products/warm-momcozy.jpg",
    url: "https://www.target.com/p/-/A-92158162",
  },
  {
    id: "warmer-baby-brezza-smart",
    category: "bottle-warmer",
    title: "Baby Brezza Smart Bottle Warmer",
    retailer: "Baby Brezza",
    price: "$89.99",
    rating: "4.4 · 705 reviews",
    badge: "Best for gaming upstairs",
    note: "Bluetooth alerts, nine presets, auto shutoff, and separate warm-water-bath and steam modes for breast milk versus formula.",
    specs: ["Phone alerts", "Warm-water bath", "18-month direct warranty"],
    image: "assets/products/warm-brezza.jpg",
    url: "https://babybrezza.com/products/safe-smart-bottle-warmer",
  },
  {
    id: "baby-chicco-lullago",
    category: "baby-space",
    title: "Chicco LullaGo Anywhere",
    retailer: "Target",
    price: "$109.99",
    rating: "4.8 · 12 Target reviews",
    badge: "Best compact newborn pick",
    note: "Twelve-pound portable bassinet with firm flat waterproof mattress, fitted sheet, mesh panels, washable fabric, and carry bag.",
    specs: ["35 × 22 × 28 in.", "GREENGUARD Gold", "Firm flat surface"],
    image: "assets/products/baby-chicco.jpg",
    url: "https://www.target.com/p/-/A-95018337",
  },
  {
    id: "baby-guava-lotus",
    category: "baby-space",
    title: "Guava Lotus Travel Crib",
    retailer: "Guava Family",
    price: "$249.95",
    rating: "4.8 · 1,587 reviews",
    badge: "Best long-term value",
    note: "A 15-pound floor-resting sleep and play space with lockable side door, backpack case, and no upper weight limit.",
    specs: ["Newborn–3 years", "GREENGUARD Gold", "45.5 × 31.5 in. footprint"],
    image: "assets/products/baby-lotus.png",
    url: "https://www.guavafamily.com/products/lotus-everywhere-travel-crib",
  },
  {
    id: "baby-newton-deluxe",
    category: "baby-space",
    title: "Newton Deluxe Travel Crib & Play Yard",
    retailer: "Newton Baby",
    price: "$299.99",
    rating: "Premium washable system",
    badge: "Roomiest washable pick",
    note: "Large 48 × 34 inch sleep surface, washable breathable mattress and mesh. Optional bassinet bundle is for newborns up to 15 pounds.",
    specs: ["Washable mattress", "GREENGUARD Gold", "Optional newborn bassinet"],
    image: "assets/products/baby-newton.jpg",
    url: "https://www.newtonbaby.com/products/travel-crib-play-yard",
  },
  {
    id: "chair-lazboy-manager",
    category: "office-chair",
    title: "La-Z-Boy Manager Office Chair",
    retailer: "Costco",
    price: "Check Costco price",
    rating: "Cushioned manager chair",
    badge: "Classic comfort",
    note: "A padded high-back manager chair with upholstered arms and a conventional rolling office base.",
    specs: ["High back", "Padded arms", "Rolling base"],
    image: null,
    url: "https://www.costco.com/p/-/la-z-boy-manager-office-chair/4000230606?langId=-1",
  },
  {
    id: "chair-lazboy-air-lumbar",
    category: "office-chair",
    title: "La-Z-Boy Air Lumbar Manager Office Chair",
    retailer: "Costco",
    price: "Check Costco price",
    rating: "Air lumbar support",
    badge: "Best postpartum comfort",
    note: "A deeply cushioned manager chair with La-Z-Boy Air lumbar support and padded flip-up arms.",
    specs: ["Air lumbar support", "Deep cushioning", "Flip-up arms"],
    image: null,
    url: "https://www.costco.com/p/-/la-z-boy-air-lumbar-manager-office-chair/4000238656?langId=-1",
  },
  {
    id: "chair-dps-centurion",
    category: "office-chair",
    title: "DPS Centurion Pedestal Swivel Chair",
    retailer: "Costco",
    price: "Check Costco price",
    rating: "Pedestal recliner",
    badge: "Best lounge option",
    note: "A wide padded pedestal chair intended for relaxed gaming and console sessions rather than desk-height task work.",
    specs: ["Pedestal swivel", "Reclining seat", "Wide padded arms"],
    image: null,
    url: "https://www.costco.com/p/-/dps-centurion-pedestal-swivel-gaming-chair/4000405043?langId=-1",
  },
  {
    id: "art-elven-reading-lamp",
    category: "light-art",
    title: "Fantasy Reading Light Elven Accent Lamp",
    retailer: "Etsy · listing 4528112096",
    price: "Live Etsy price",
    rating: "Elven crystal design",
    badge: "Best fantasy accent",
    note: "A glowing blue crystal lamp in an ornate elven-style base for a reading nook, desk, or shelf.",
    specs: ["Crystal light", "Elven-style base", "Accent lamp"],
    image: "assets/products/ffxiv_crystal.png",
    url: "https://www.etsy.com/listing/4528112096/fantasy-reading-light-elven-accent-lamp",
  },
  {
    id: "art-ffxiv-lightbox",
    category: "light-art",
    title: "FINAL FANTASY XIV Amaurot Light Box",
    retailer: "Etsy · listing 1266023475",
    price: "Live Etsy price",
    rating: "Gaming room light box",
    note: "A layered FFXIV light box intended as a desk lamp, night light, or illuminated room accent.",
    specs: ["Layered light box", "Desk or wall decor", "Made to order"],
    image: "assets/products/ffxiv_amaurot.png",
    url: "https://www.etsy.com/listing/1266023475/final-fantasy-xiv-light-box-gaming-room",
  },
  {
    id: "art-ffx-led",
    category: "light-art",
    title: "FINAL FANTASY X RGB Wall Sign",
    retailer: "Etsy · listing 4436435478",
    price: "Live Etsy price",
    rating: "Edge-lit RGB acrylic",
    note: "A dedicated FFX wall sign with edge-lit RGB illumination for the game room.",
    specs: ["RGB edge lighting", "Wall decor", "FFX design"],
    image: null,
    url: "https://www.etsy.com/listing/4436435478/final-fantasy-x-led-wall-decor-sign-game",
  },
  {
    id: "art-crystal-cluster",
    category: "light-art",
    title: "Enchanted Crystal Cluster Mushroom Lamp",
    retailer: "Etsy · listing 4387350870",
    price: "Live Etsy price",
    rating: "Handmade fantasy lamp",
    badge: "Best magical-room light",
    note: "A handmade illuminated crystal-and-mushroom scene under a glass dome with a wooden base.",
    specs: ["Glass dome", "Crystal cluster", "Illuminated mushrooms"],
    image: "assets/products/ffxiv_mushroom_lamp.png",
    url: "https://www.etsy.com/listing/4387350870/enchanted-crystal-cluster-lamp-mushroom",
  },
  {
    id: "mat-lulu-custom-rgb",
    category: "desk-mat",
    title: "Custom Artwork LED RGB Gaming Mouse Pad",
    retailer: "Etsy · listing 4541938011",
    price: "Live Etsy price",
    rating: "Personalized illuminated mat",
    badge: "Use Lulu's final artwork",
    note: "Upload Lulu's final artwork for a personalized desk mat with illuminated RGB edging.",
    specs: ["Custom artwork", "RGB edge lighting", "Extended desk format"],
    image: null,
    url: "https://www.etsy.com/listing/4541938011/custom-artwork-led-gaming-mouse-pad-rgb",
  },
  {
    id: "desk-opnice-pink-riser",
    category: "desk-mat",
    title: "OPNICE Pink Dual Monitor Riser",
    retailer: "Amazon",
    price: "$32.39",
    rating: "4.6 · 1,103 reviews",
    badge: "Best pink organization",
    note: "A pink adjustable dual-monitor riser with a drawer and two pen holders that arrives with minimal assembly.",
    specs: ["Dual monitor support", "Drawer + pen holders", "Pink metal finish"],
    image: "assets/products/desk-opnice-pink.jpg",
    url: "https://www.amazon.com/OPNICE-Organizers-Accessories-Workspace-Organization/dp/B0F6NGVQWG/",
  },
  {
    id: "desk-fenge-oak-riser",
    category: "desk-mat",
    title: "Fenge 42.5-inch Dual Monitor Riser",
    retailer: "Amazon",
    price: "$89.99",
    rating: "4.6 · 329 reviews",
    badge: "Best complete desk shelf",
    note: "A 42.5-inch oak monitor riser with two tiers, two drawers, cable management, and support for up to 99 pounds.",
    specs: ["42.5 × 9.3 × 5.5 in.", "Two drawers", "99 lb capacity"],
    image: "assets/products/desk-fenge-oak.jpg",
    url: "https://www.amazon.com/Fenge-Monitor-42-5inch-Computer-Organizer/dp/B0CRHCKDVW/",
  },
];
