window.PUSH_PRESENT_CATEGORIES = [
  {
    id: "milk-fridge",
    title: "Upstairs Milk Fridge",
    subtitle: "True compressor refrigerators only",
    note: "Breast milk must stay at 40°F / 4°C or colder. Add an appliance thermometer and verify the temperature before storing milk. Cosmetic thermoelectric coolers were excluded.",
    icon: "currency.png",
  },
  {
    id: "bottle-warmer",
    title: "Bottle Warmer",
    subtitle: "Fast feeds beside the gaming desk",
    note: "Warm water-bath models are gentler for breast milk. Always swirl and test the milk temperature before feeding.",
    icon: "recommendations.png",
  },
  {
    id: "baby-space",
    title: "Baby's Craft-Room Space",
    subtitle: "A safe place nearby while Lulu games",
    note: "Floor use only. For sleep, use a CPSC-compliant crib, bassinet, portable crib, or play yard with a firm flat surface and fitted sheet only. Never place or anchor one on a tabletop.",
    icon: "recommendations.png",
  },
  {
    id: "office-chair",
    title: "Healing-Friendly Chair",
    subtitle: "Cute enough for Lulu, adjustable enough for long sessions",
    note: "Comfort is personal, so prioritize a generous return window. These options provide substantially better adjustability than novelty-only gaming chairs.",
    icon: "recommendations.png",
  },
  {
    id: "light-art",
    title: "Light-Up Final Fantasy Art",
    subtitle: "Eorzea, Amaurot, Spira, and Vana'diel",
    note: "Etsy prices and availability change frequently. The links open the exact indexed listing where available; confirm seller details before ordering.",
    icon: "glamour_plate.png",
  },
  {
    id: "desk-mat",
    title: "Desk Mat",
    subtitle: "Full-desk RGB or custom Lulu Prissypants art",
    note: "Measure the usable desktop before choosing. The largest verified RGB option here is 48 × 20 inches.",
    icon: "limit_break.png",
  },
  {
    id: "keycaps",
    title: "FFXIV Keycaps",
    subtitle: "Job icons, Eorzean letters, or Lulu herself",
    note: "Confirm her keyboard uses Cherry MX-style cross stems and check its layout before ordering a set.",
    icon: "achievements.png",
  },
  {
    id: "desktop",
    title: "Desktop",
    subtitle: "A clean top for the whole setup",
    note: "IKEA tabletops are designed for compatible underframes. Confirm the current frame width and mounting pattern before buying.",
    icon: "inventory.png",
  },
];

window.PUSH_PRESENT_PRODUCTS = [
  {
    id: "fridge-frigidaire-pink-16",
    category: "milk-fridge",
    title: "Frigidaire 1.6 cu. ft. Retro Refrigerator",
    retailer: "Walmart",
    price: "$118.00",
    rating: "4.1 · 1,399 reviews",
    badge: "Cutest compact pick",
    note: "Pink compressor refrigerator with chiller compartment and side bottle opener. Small enough for an upstairs office without relying on thermoelectric cooling.",
    specs: ["1.6 cu. ft.", "Pink retro shell", "Adjustable thermostat"],
    image: "assets/products/fridge-frigidaire-pink.jpg",
    url: "https://www.walmart.com/ip/983936626",
  },
  {
    id: "fridge-bangson-pink-17",
    category: "milk-fridge",
    title: "BANGSON 1.7 cu. ft. Mini Fridge",
    retailer: "Walmart",
    price: "$119.99",
    rating: "4.5 · 44 reviews",
    badge: "Best pink value",
    note: "A pink compressor model with freezer compartment, low-noise positioning, and more conventional interior storage.",
    specs: ["1.7 cu. ft.", "Freezer compartment", "Low-noise design"],
    image: "assets/products/fridge-bangson-pink.jpg",
    url: "https://www.walmart.com/ip/18938167803",
  },
  {
    id: "fridge-frigidaire-coral-32",
    category: "milk-fridge",
    title: "Frigidaire 3.2 cu. ft. Retro Refrigerator",
    retailer: "Walmart",
    price: "$158.00",
    rating: "4.0 · 2,088 reviews",
    badge: "Best capacity",
    note: "Coral retro refrigerator with chiller and substantially more room for milk, drinks, pump parts, and snacks.",
    specs: ["3.2 cu. ft.", "Coral finish", "Chiller compartment"],
    image: "assets/products/fridge-frigidaire-coral.jpg",
    url: "https://www.walmart.com/ip/598804573",
  },
  {
    id: "fridge-frigidaire-pink-32",
    category: "milk-fridge",
    title: "Frigidaire 3.2 cu. ft. Retro Refrigerator in Pink",
    retailer: "Walmart",
    price: "Check current price",
    rating: "Full-size compact option",
    badge: "Roomiest pink pick",
    note: "The pink version of the larger compressor refrigerator, with room for bottles, pump parts, drinks, and snacks.",
    specs: ["3.2 cu. ft.", "Pink retro finish", "Adjustable thermostat"],
    image: "assets/products/fridge-frigidaire-pink.jpg",
    url: "https://www.walmart.com/search?q=Frigidaire+3.2+cu+ft+retro+refrigerator+pink",
  },
  {
    id: "fridge-bangson-white-17",
    category: "milk-fridge",
    title: "BANGSON 1.7 cu. ft. Mini Fridge in White",
    retailer: "Walmart",
    price: "Check current price",
    rating: "Compact compressor model",
    badge: "Best clean white pick",
    note: "A clean white alternative to the pink BANGSON with the same compact footprint and separate freezer compartment.",
    specs: ["1.7 cu. ft.", "White finish", "Freezer compartment"],
    image: "assets/products/fridge-bangson-pink.jpg",
    url: "https://www.walmart.com/search?q=BANGSON+1.7+cu+ft+mini+fridge+white",
  },
  {
    id: "warmer-philips-avent",
    category: "bottle-warmer",
    title: "Philips Avent Premium Fast Warmer",
    retailer: "Target",
    price: "$46.99",
    rating: "3.6 · 778 ratings",
    badge: "Simplest controls",
    note: "Smart temperature control detects starting temperature, warms evenly, defrosts, and holds temperature for up to 60 minutes.",
    specs: ["Auto shutoff", "No hot spots", "Defrost mode"],
    image: "assets/products/warm-philips.png",
    url: "https://www.target.com/p/-/A-80178789",
  },
  {
    id: "warmer-momcozy-mw01",
    category: "bottle-warmer",
    title: "Momcozy MW01 6-in-1 Warmer",
    retailer: "Target",
    price: "$33.99",
    rating: "4.1 · 344 ratings",
    badge: "Best value",
    note: "Fast 2–5 minute warming plus thaw, food heat, steam, and keep-warm modes. Fits bottles and milk bags up to 11 oz.",
    specs: ["2–5 minute warm", "Fits milk bags", "6 functions"],
    image: "assets/products/warm-momcozy.jpg",
    url: "https://www.target.com/p/-/A-92158162",
  },
  {
    id: "warmer-baby-brezza-smart",
    category: "bottle-warmer",
    title: "Baby Brezza Smart Bottle Warmer",
    retailer: "Baby Brezza",
    price: "$89.99",
    rating: "4.4 · 705 reviews",
    badge: "Best for gaming upstairs",
    note: "Bluetooth alerts, nine presets, auto shutoff, and separate warm-water-bath and steam modes for breast milk versus formula.",
    specs: ["Phone alerts", "Warm-water bath", "18-month direct warranty"],
    image: "assets/products/warm-brezza.jpg",
    url: "https://babybrezza.com/products/safe-smart-bottle-warmer",
  },
  {
    id: "baby-chicco-lullago",
    category: "baby-space",
    title: "Chicco LullaGo Anywhere",
    retailer: "Target",
    price: "$109.99",
    rating: "4.8 · 12 Target reviews",
    badge: "Best compact newborn pick",
    note: "Twelve-pound portable bassinet with firm flat waterproof mattress, fitted sheet, mesh panels, washable fabric, and carry bag.",
    specs: ["35 × 22 × 28 in.", "GREENGUARD Gold", "Firm flat surface"],
    image: "assets/products/baby-chicco.jpg",
    url: "https://www.target.com/p/-/A-95018337",
  },
  {
    id: "baby-guava-lotus",
    category: "baby-space",
    title: "Guava Lotus Travel Crib",
    retailer: "Guava Family",
    price: "$249.95",
    rating: "4.8 · 1,587 reviews",
    badge: "Best long-term value",
    note: "A 15-pound floor-resting sleep and play space with lockable side door, backpack case, and no upper weight limit.",
    specs: ["Newborn–3 years", "GREENGUARD Gold", "45.5 × 31.5 in. footprint"],
    image: "assets/products/baby-lotus.png",
    url: "https://www.guavafamily.com/products/lotus-everywhere-travel-crib",
  },
  {
    id: "baby-newton-deluxe",
    category: "baby-space",
    title: "Newton Deluxe Travel Crib & Play Yard",
    retailer: "Newton Baby",
    price: "$299.99",
    rating: "Premium washable system",
    badge: "Roomiest washable pick",
    note: "Large 48 × 34 inch sleep surface, washable breathable mattress and mesh. Optional bassinet bundle is for newborns up to 15 pounds.",
    specs: ["Washable mattress", "GREENGUARD Gold", "Optional newborn bassinet"],
    image: "assets/products/baby-newton.jpg",
    url: "https://www.newtonbaby.com/products/travel-crib-play-yard",
  },
  {
    id: "chair-branch-ergonomic",
    category: "office-chair",
    title: "Branch Ergonomic Chair",
    retailer: "Branch",
    price: "$323.10 sale",
    rating: "4.5 · 7,140 reviews",
    badge: "Best value ergonomics",
    note: "White frame option, high-density cushion, adjustable seat depth and lumbar, 3D arms, and optional headrest.",
    specs: ["8 adjustments", "275 lb capacity", "7-year warranty"],
    image: "assets/products/chair-branch.jpg",
    url: "https://www.branchfurniture.com/products/ergonomic-chair",
  },
  {
    id: "chair-branch-verve-coral",
    category: "office-chair",
    title: "Branch Verve Chair in Coral",
    retailer: "Branch",
    price: "$539.10 sale",
    rating: "4.5 · 888 reviews",
    badge: "Best cute + ergonomic",
    note: "Soft coral color, cloud-like cushion, breathable knit, adjustable lumbar and seat depth, with an optional headrest.",
    specs: ["6 adjustments", "Best for 5'0–6'0", "7-year warranty"],
    image: "assets/products/chair-verve.png",
    url: "https://www.branchfurniture.com/products/verve-chair",
  },
  {
    id: "chair-steelcase-series-1",
    category: "office-chair",
    title: "Steelcase Series 1",
    retailer: "Steelcase",
    price: "Check current price",
    rating: "Performance office chair",
    badge: "Best proven office chair",
    note: "A compact ergonomic office chair with weight-activated controls, adjustable lumbar support, and multiple arm configurations.",
    specs: ["Adjustable lumbar", "Weight-activated controls", "12-year warranty"],
    image: "assets/products/chair-steelcase-series-1.jpg",
    url: "https://www.steelcase.com/products/office-chairs/steelcase-series-1/",
  },
  {
    id: "art-elven-reading-lamp",
    category: "light-art",
    title: "Fantasy Reading Light Elven Accent Lamp",
    retailer: "Etsy · listing 4528112096",
    price: "Live Etsy price",
    rating: "Elven crystal design",
    badge: "Best fantasy accent",
    note: "A glowing blue crystal lamp in an ornate elven-style base for a reading nook, desk, or shelf.",
    specs: ["Crystal light", "Elven-style base", "Accent lamp"],
    image: "assets/art/aymeric.webp",
    url: "https://www.etsy.com/listing/4528112096/fantasy-reading-light-elven-accent-lamp",
  },
  {
    id: "art-ffxiv-lightbox",
    category: "light-art",
    title: "FINAL FANTASY XIV Amaurot Light Box",
    retailer: "Etsy · listing 1266023475",
    price: "Live Etsy price",
    rating: "Gaming room light box",
    note: "A layered FFXIV light box intended as a desk lamp, night light, or illuminated room accent.",
    specs: ["Layered light box", "Desk or wall decor", "Made to order"],
    image: "assets/art/emet-selch.webp",
    url: "https://www.etsy.com/listing/1266023475/final-fantasy-xiv-light-box-gaming-room",
  },
  {
    id: "art-ffx-led",
    category: "light-art",
    title: "FINAL FANTASY X RGB Wall Sign",
    retailer: "Etsy · listing 4436435478",
    price: "Live Etsy price",
    rating: "Edge-lit RGB acrylic",
    note: "A dedicated FFX wall sign with edge-lit RGB illumination for the game room.",
    specs: ["RGB edge lighting", "Wall decor", "FFX design"],
    image: "assets/art/estinien.webp",
    url: "https://www.etsy.com/listing/4436435478/final-fantasy-x-led-wall-decor-sign-game",
  },
  {
    id: "art-crystal-cluster",
    category: "light-art",
    title: "Enchanted Crystal Cluster Mushroom Lamp",
    retailer: "Etsy · listing 4387350870",
    price: "Live Etsy price",
    rating: "Handmade fantasy lamp",
    badge: "Best magical-room light",
    note: "A handmade illuminated crystal-and-mushroom scene under a glass dome with a wooden base.",
    specs: ["Glass dome", "Crystal cluster", "Illuminated mushrooms"],
    image: "assets/art/hythlodaeus.webp",
    url: "https://www.etsy.com/listing/4387350870/enchanted-crystal-cluster-lamp-mushroom",
  },
  {
    id: "mat-lulu-custom",
    category: "desk-mat",
    title: "Hand-Drawn Custom Character Desk Mat",
    retailer: "Etsy · listing 4333426431",
    price: "Live Etsy price",
    rating: "Mockup approval included",
    badge: "Best Lulu Prissypants pick",
    note: "The artist draws Lulu from references and sends a digital mockup for approval before producing the mat.",
    specs: ["Original character art", "Proof before production", "Limited slots"],
    image: "assets/art/lulu-prissypants-presenting.png",
    url: "https://www.etsy.com/listing/4333426431/custom-character-desk-mat-hand-drawn",
  },
  {
    id: "mat-eorzea-map",
    category: "desk-mat",
    title: "Eorzea World Map Desk Mat",
    retailer: "Etsy · listing 1638471562",
    price: "Live Etsy price",
    rating: "Three Continents map",
    note: "A broad Eorzea and Hydaelyn map print suited to a full keyboard-and-mouse workspace.",
    specs: ["World map print", "Extended format", "Non-slip desk pad"],
    image: "assets/art/graha-tia.webp",
    url: "https://www.etsy.com/listing/1638471562/ffxiv-world-map-desk-mat-three",
  },
  {
    id: "mat-cacoy-rgb",
    category: "desk-mat",
    title: "Cacoy 48 × 20 RGB Desk Mat",
    retailer: "Amazon",
    price: "$37.99",
    rating: "4.4 · 753 reviews",
    badge: "Largest RGB pick",
    note: "The largest verified RGB mat in the research, with nine lighting modes, stitched edges, and non-slip rubber base.",
    specs: ["48 × 20 in.", "9 RGB modes", "3 mm thick"],
    image: "assets/products/mat-cacoy.jpg",
    url: "https://www.amazon.com/dp/B0F4KKS3LQ",
  },
  {
    id: "mat-bladehawks-rgb",
    category: "desk-mat",
    title: "BladeHawks RGB Extended Mat",
    retailer: "Amazon",
    price: "$14.99",
    rating: "4.7 · 15,777 reviews",
    badge: "Best proven value",
    note: "A highly reviewed 31.5 × 12 inch mat with 14 modes, waterproof cloth surface, and power-off memory.",
    specs: ["31.5 × 12 in.", "14 light modes", "Waterproof surface"],
    image: "assets/products/mat-bladehawks.jpg",
    url: "https://www.amazon.com/dp/B07L4BGL3D",
  },
  {
    id: "mat-jmiyav-pink",
    category: "desk-mat",
    title: "JMIYAV Pink RGB Desk Mat",
    retailer: "Amazon",
    price: "$29.98 Prime",
    rating: "New listing · 5.0",
    badge: "Cutest ready-made RGB",
    note: "Pink 31.5 × 12 inch desk mat with 13 modes, memory, waterproof surface, and soft braided fabric.",
    specs: ["31.5 × 12 in.", "13 light modes", "Pink printed surface"],
    image: "assets/products/mat-pink.jpg",
    url: "https://www.amazon.com/dp/B0G6MRZSP2",
  },
  {
    id: "keys-eorzean-alphabet",
    category: "keycaps",
    title: "Eorzean Alphabet Keycap Set",
    retailer: "Etsy · HelicalHearth",
    price: "Live Etsy price",
    rating: "5.0 shop rating",
    badge: "Most distinctly FFXIV",
    note: "A complete Eorzean alphabet treatment rather than a single novelty key.",
    specs: ["Alphabet set", "Mechanical keyboards", "Made to order"],
    image: "assets/products/keycaps-custom.jpg",
    url: "https://www.etsy.com/listing/1027219539/ffxiv-keycap-set-eorzean-alphabet",
  },
  {
    id: "keys-job-symbols",
    category: "keycaps",
    title: "FFXIV Job Symbol Keycap Set",
    retailer: "Etsy · HelicalHearth",
    price: "Live Etsy price",
    rating: "5.0 shop rating",
    note: "A set built around Final Fantasy XIV job symbols for a more colorful, recognizable layout.",
    specs: ["Job icon set", "MX-style switches", "Multiple material choices"],
    image: "assets/ffxiv/glamour_plate.png",
    url: "https://www.etsy.com/listing/994274896/ffxiv-keycap-set-final-fantasy-jobs",
  },
  {
    id: "keys-backlit-alphabet",
    category: "keycaps",
    title: "Eorzean Backlit 26-Key Set",
    retailer: "Etsy · MaxKeycap",
    price: "Live Etsy price",
    rating: "A–Z · 26 keys",
    note: "A shine-through Eorzean alphabet set compatible with common Keychron, GMMK, Corsair, and Razer mechanical boards.",
    specs: ["26 keys", "Backlight compatible", "Common MX boards"],
    image: "assets/products/keycap-dragon.jpg",
    url: "https://www.etsy.com/listing/1732466766/ffxiv-eorzean-alphabet-backlit-keycap",
  },
  {
    id: "keys-job-stone",
    category: "keycaps",
    title: "Job Stone Soul Crystal Keycap",
    retailer: "Etsy · listing 4503930877",
    price: "Live Etsy price",
    rating: "Handmade resin · MOA 1U",
    note: "A single shimmering resin job-stone key with a sealed white job symbol for the escape-key position.",
    specs: ["1U MOA profile", "Handmade resin", "Choose her job"],
    image: "assets/ffxiv/limit_break.png",
    url: "https://www.etsy.com/listing/4503930877/ffxiv-job-stone-soul-crystal-keycap-moa",
  },
  {
    id: "keys-lulu-custom",
    category: "keycaps",
    title: "Custom Lulu Prissypants Keycap Set",
    retailer: "Amazon · Gloryage",
    price: "$36.99 from",
    rating: "5.0 · 6 reviews",
    badge: "Most personal",
    note: "Upload Lulu's artwork for a custom PBT set. Available in multiple set sizes for Cherry MX-style switches; customized orders are non-returnable.",
    specs: ["Upload artwork", "PBT", "Cherry MX compatible"],
    image: "assets/products/keycaps-custom.jpg",
    url: "https://www.amazon.com/dp/B0G827HYH4",
  },
  {
    id: "desktop-lagkapten-white",
    category: "desktop",
    title: "IKEA LAGKAPTEN White Top",
    retailer: "IKEA",
    price: "$49.99",
    rating: "4.3 · 859 reviews",
    badge: "Best clean white value",
    note: "A bright 55⅛ × 23⅝ inch top with a simple finish and a 365-day IKEA return window.",
    specs: ["55⅛ × 23⅝ in.", "White", "Constructed board"],
    image: "assets/products/desktop-white.jpg",
    url: "https://www.ikea.com/us/en/p/lagkapten-tabletop-white-40460815/",
  },
  {
    id: "desktop-anfallare-bamboo",
    category: "desktop",
    title: "IKEA ANFALLARE Bamboo Top",
    retailer: "IKEA",
    price: "$99.99",
    rating: "4.5 · 208 reviews",
    note: "A warmer, stronger-looking 55⅛ × 25⅝ inch bamboo surface if Lulu prefers natural texture over pure white.",
    specs: ["55⅛ × 25⅝ in.", "Bamboo", "Deeper work surface"],
    image: "assets/products/desktop-bamboo.jpg",
    url: "https://www.ikea.com/us/en/p/anfallare-tabletop-bamboo-00465141/",
  },
];
